-- 1.ELENCARE IL NUMERO DI TRACCE IN ORDINE DISCENDENTE, ESCLUDENDO QUEI GENERI CHE HANNO MENO DI 10 TRACCE
SELECT COUNT(DISTINCT T.Name) AS NUMERO_DI_TRACCE, G.Name AS GENERE
FROM track T LEFT JOIN  genre G ON T.GenreId=G.GenreId
GROUP BY G.Name
HAVING COUNT(DISTINCT T.Name) >= 10
ORDER BY COUNT(DISTINCT T.Name) DESC;

-- 2.TROVARE LE 3 CANZONI PIù COSTOSE
SELECT T.Name, T.UnitPrice
FROM track T
WHERE MediaTypeId <> 3
ORDER BY T.UnitPrice DESC
LIMIT 3;

-- 3.ELENCARE GLI ARTISTI CHE HANNO CANZONI PIù LUNGHE DI 6 MINUTI
SELECT DISTINCT (AR.Name) AS ARTISTA
FROM track T LEFT JOIN album AL ON T.AlbumId=AL.AlbumId
LEFT JOIN artist AR ON AL.ArtistId=AR.ArtistId
WHERE T.Milliseconds/60000 >6 AND MediaTypeId <> 3;

-- 4.INDIVIDUARE LA DURATA MEDIA DELLE TRACCE PER OGNI GENERE
SELECT G.Name AS GENERE, CAST(AVG(T.Milliseconds)/60000 AS DECIMAL (5,3)) AS DURATA_MIN
FROM track T LEFT JOIN  genre G ON T.GenreId=G.GenreId
GROUP BY G.Name
ORDER BY CAST(AVG(T.Milliseconds)/60000 AS DECIMAL (5,3)) DESC;

-- 5. ELENCARE TUTTE LE CANZONI CON LA PAROLA LOVE NEL TITOLO, ORDINANDOLE ALFABETICAMENTE PRIMA PER GENERE E POI PER NOME.
SELECT DISTINCT T.Name AS TITOLO, G.Name AS GENERE
FROM track T LEFT JOIN  genre G ON T.GenreId=G.GenreId
WHERE T.Name LIKE "%LOVE%" AND T.Name NOT LIKE '%LLOVE%'
ORDER BY G.Name, T.Name;

-- 6.TROVARE IL COSTO MEDIO PER OGNI TIPOLOGIA DI MEDIA
SELECT M.Name AS TIPOLOGIA_MEDIA, CAST(AVG(UNITPRICE) AS DECIMAL(10,2)) AS COSTO_MEDIO
FROM track T LEFT JOIN mediatype M ON T.MediaTypeId=M.MediaTypeId
GROUP BY M.Name
ORDER BY COSTO_MEDIO DESC;

-- 7.INDIVIDUARE IL GENERE CON PIù TRACCE
SELECT G.Name AS GENERE, COUNT(DISTINCT T.Name) AS NUMERO_TRACCE 
FROM track T LEFT JOIN  genre G ON T.GenreId=G.GenreId
GROUP BY G.Name
ORDER BY NUMERO_TRACCE DESC
LIMIT 1;


-- 8. TROVARE GLI ARTISTI CHE HANNO LO STESSO NUMERO DI ALBUM DEI ROLLING STONES
SELECT AR.Name,COUNT(DISTINCT AL.Title) AS NUMERO_ALBUM
FROM album AL LEFT JOIN artist AR ON AL.ArtistId=AR.ArtistId
GROUP BY AR.Name
HAVING NUMERO_ALBUM = (SELECT COUNT(DISTINCT A.Title)
FROM album A LEFT JOIN artist B ON A.ArtistId=B.ArtistId
WHERE B.Name LIKE "THE ROLLING STONES"
GROUP BY B.Name);


-- 9.TROVARE L'ARTISTA CON L'ALBUM PIù COSTOSO
SELECT AR.Name AS ARTISTA, AL.Title AS ALBUM, SUM(T.UnitPrice) AS COSTO_ALBUM 
FROM track T LEFT JOIN album AL ON T.AlbumId=AL.AlbumId
LEFT JOIN artist AR ON AL.ArtistId=AR.ArtistId
GROUP BY AR.Name, AL.Title
ORDER BY  COSTO_ALBUM DESC
LIMIT 1;

